# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.lhjzzu.com
date_format: "ordinal"
title: 静心
subtitle: ""
description: "刘华健个人博客"
keywords: 码志, Zhuang Ma, mzlogin, mazhuang
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/lhjzzu/lhjzzu.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: Liu Hua Jian
organization: ouer, Inc.
organization_url: https://www.kkkd.com
location: HangZhou, China
email: 1822657131@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: lhjzzu
weibo_username: lhjzzu1991
#zhihu_username:lhjzzu

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: abc19911991
#disqus_username: abc19911991

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [OC]
skill_mobile_app_keywords: [IOS]
skill_windows_keywords: []
popular_repos: ['lhjzzu.github.io']
#contribute_repos: ['sparanoid/chinese-copywriting-guidelines', 'waylife/RentCrawer']
